name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30  # 增加超时时间至30分钟
    strategy:
      max-parallel: 4 # 一次最多并行运行 2 个构建任务
      matrix:
        include:
        #   - os: ubuntu-latest
        #     platform: 'linux-x86_64'
        #     rust_target: 'x86_64-unknown-linux-gnu'
          # - os: macos-latest
          #   platform: 'darwin-x86_64'
          #   rust_target: 'x86_64-apple-darwin'
          # - os: macos-14
          #   platform: 'darwin-aarch64'
          #   rust_target: 'aarch64-apple-darwin'
          # - os: windows-latest
          #   platform: 'windows-x86_64'
          #   rust_target: 'x86_64-pc-windows-msvc'
          - os: ubuntu-latest
            platform: 'android'
            rust_target: 'aarch64-linux-android' 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Cache Rust dependencies
      uses: swatinem/rust-cache@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'yarn'

    - name: Set up Java for Android build
      if: matrix.platform == 'android'
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Android SDK
      if: matrix.platform == 'android'
      uses: android-actions/setup-android@v3

    - name: Install NDK and set NDK_HOME
      if: matrix.platform == 'android'
      run: |
        echo "y" | ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager "ndk;25.1.8937393"
        echo "NDK_HOME=${ANDROID_HOME}/ndk/25.1.8937393" >> $GITHUB_ENV

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.rust_target }}
        components: rust-src # for android

    - name: Install additional Rust targets for Android
      if: matrix.platform == 'android'
      run: |
        rustup target add armv7-linux-androideabi
        rustup target add x86_64-linux-android

    - name: Install Rust dependencies for Linux
      if: matrix.os == 'ubuntu-latest' && matrix.platform != 'android'
      run: |
        sudo apt-get update
        sudo apt-get install -y libwebkit2gtk-4.1-0 libappindicator3-1 libgtk-3-0 patchelf

    - name: Install dependencies
      run: yarn install --frozen-lockfile
      
    - name: Setup Android signing
      if: matrix.platform == 'android'
      run: |
        KEYSTORE_PATH=$RUNNER_TEMP/keystore.jks
        echo "storeFile=$KEYSTORE_PATH" > src-tauri/keystore.properties
        echo "storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" >> src-tauri/keystore.properties
        echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> src-tauri/keystore.properties
        echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> src-tauri/keystore.properties
        echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > $KEYSTORE_PATH

    - name: Import Apple Certificate
      if: runner.os == 'macOS'
      uses: apple-actions/import-codesign-certs@v2
      with:
        p12-file-base64: ${{ secrets.MACOS_CERTIFICATE }}
        p12-password: ${{ secrets.MACOS_CERTIFICATE_PASSWORD }}

    - name: Build the application
      if: matrix.platform != 'android'
      run: yarn tauri build --target ${{ matrix.rust_target }}
      env:
        TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
        TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}

    - name: Build Android App Bundle (AAB)
      if: matrix.platform == 'android'
      run: |
        rm -rf src-tauri/gen
        yarn tauri android init
        yarn tauri android build --target aarch64 --target armv7
      env:
        TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
        TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: tauri-build-${{ matrix.platform }}
        path: |
          src-tauri/target/${{ matrix.rust_target }}/release/bundle/

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write # 允许上传 Release 产物
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: src-tauri/target/

    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

    - name: Generate update manifest
      id: generate_manifest
      run: |
        # 赋予执行权限
        chmod +x scripts/generate-update-manifest.cjs
        # 运行脚本
        node scripts/generate-update-manifest.cjs
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
        RELEASE_NOTES: "See the release notes for details."
        npm_package_version: ${{ steps.get_version.outputs.VERSION }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: 'Release ${{ github.ref_name }}'
        body: |
          Automated release for version ${{ github.ref_name }}.
        draft: false
        prerelease: false

    - name: Upload Release Assets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -x # 开启调试模式

        # 定义根目录
        TARGET_DIR="src-tauri/target"
        VERSION="${{ steps.get_version.outputs.VERSION }}"

        # 创建一个临时目录来整理所有待上传的文件
        UPLOAD_DIR=$(mktemp -d)
        
        # 查找并移动 Linux 产物
        # find "$TARGET_DIR/tauri-build-linux-x86_64/appimage" -name "*.AppImage" -exec mv {} "$UPLOAD_DIR/mytips-${VERSION}-amd64.AppImage" \;
        # find "$TARGET_DIR/tauri-build-linux-x86_64/appimage" -name "*.AppImage.tar.gz" -exec mv {} "$UPLOAD_DIR/mytips-${VERSION}-amd64.AppImage.tar.gz" \;
        # find "$TARGET_DIR/tauri-build-linux-x86_64/appimage" -name "*.AppImage.tar.gz.sig" -exec mv {} "$UPLOAD_DIR/mytips-${VERSION}-amd64.AppImage.tar.gz.sig" \;

        # 查找并移动 macOS x64 产物
        find "$TARGET_DIR/tauri-build-darwin-x86_64/macos" -name "*.app.tar.gz" -exec mv {} "$UPLOAD_DIR/mytips-${VERSION}-x86_64.app.tar.gz" \;
        find "$TARGET_DIR/tauri-build-darwin-x86_64/macos" -name "*.app.tar.gz.sig" -exec mv {} "$UPLOAD_DIR/mytips-${VERSION}-x86_64.app.tar.gz.sig" \;
        find "$TARGET_DIR/tauri-build-darwin-x86_64/dmg" -name "*.dmg" -exec mv {} "$UPLOAD_DIR/mytips-${VERSION}-x86_64.dmg" \;

        # 查找并移动 macOS aarch64 产物
        find "$TARGET_DIR/tauri-build-darwin-aarch64/macos" -name "*.app.tar.gz" -exec mv {} "$UPLOAD_DIR/mytips-${VERSION}-aarch64.app.tar.gz" \;
        find "$TARGET_DIR/tauri-build-darwin-aarch64/macos" -name "*.app.tar.gz.sig" -exec mv {} "$UPLOAD_DIR/mytips-${VERSION}-aarch64.app.tar.gz.sig" \;
        find "$TARGET_DIR/tauri-build-darwin-aarch64/dmg" -name "*.dmg" -exec mv {} "$UPLOAD_DIR/mytips-${VERSION}-aarch64.dmg" \;
        
        # 查找并移动 Windows 产物 (NSIS)
        find "$TARGET_DIR/tauri-build-windows-x86_64/nsis" -name "*_x64-setup.exe" -exec mv {} "$UPLOAD_DIR/mytips-${VERSION}-x64-setup.exe" \;
        find "$TARGET_DIR/tauri-build-windows-x86_64/nsis" -name "*_x64-setup.nsis.zip" -exec mv {} "$UPLOAD_DIR/mytips-${VERSION}-x64-setup.nsis.zip" \;
        find "$TARGET_DIR/tauri-build-windows-x86_64/nsis" -name "*_x64-setup.nsis.zip.sig" -exec mv {} "$UPLOAD_DIR/mytips-${VERSION}-x64-setup.nsis.zip.sig" \;
        
        # 查找并移动 Android 产物 (AAB)
        find "$TARGET_DIR/tauri-build-android/android-artifacts/release/apk" -name "*.aab" -exec mv {} "$UPLOAD_DIR/mytips-${VERSION}-android-release.aab" \;

        # 查找并移动清单文件
        find dist/update-manifests -name "*.json" -exec mv {} "$UPLOAD_DIR/" \;

        # 显示所有待上传的文件
        ls -l "$UPLOAD_DIR"

        # 使用 gh cli 上传所有文件
        gh release upload ${{ github.ref_name }} "$UPLOAD_DIR"/* 